version: "3.5"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/phishing/Dockerfile
    depends_on:
      - mongodb
    env_file:
      - ./packages/phishing/.env
    ports:
      - 5000:5000

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      args:
        API_URL: http://localhost:5000
    ports:
      - 3000:80

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db_data:/data/db

volumes:
  db_data:
